const fs=require('fs'),path=require('path'),assert=require('assert/strict'),Module=require('module'),ts=require('typescript');
const root=path.resolve(__dirname,'../..'),engine=require(path.join(root,'.typology-matrix-build/src/components/amphitheaterPrototype.js')),fixture=require('../full-domain-validation/fixture.json');
const analysis=engine.analyzeSourceGeometry(fixture.source,true),regions=new Map([...analysis.letters,...analysis.voids].map(r=>[r.id,r])),edges=new Set(analysis.relationships.map(e=>e.id)),members=new Set(fixture.source.map(p=>`${p.cell.id}@${p.sourceIndex??'member'}:${p.layerIndex??0}`));
for(const r of regions.values()){assert(r.memberIds?.length);r.memberIds.forEach(id=>assert(members.has(id),id));}
for(const e of analysis.relationships){assert(e.id);assert(regions.has(e.fromId)&&regions.has(e.toId));}
const rows=[];
for(const typology of ['contained-room-within-volume','flat-deep-plan-plate','vertical-void-lobby'])for(const mode of ['letters','voids','combined']){
 const args={...fixture,sourceAnalysis:analysis,typology,mode,quality:'preview'},r=engine.generateProtoArchitecture(args);
 for(const e of r.elements){assert(e.provenance);assert.equal(e.provenance.architecturalElementId,e.id);e.provenance.sourceRegionIds.forEach(id=>assert(regions.has(id)));e.provenance.sourceRelationshipIds.forEach(id=>assert(edges.has(id)));e.provenance.sourceLetterIds.forEach(id=>assert(members.has(id)));}
 const modified=structuredClone(fixture.descriptors);modified.openVolume.intensity=85;const changed=engine.generateProtoArchitecture({...args,descriptors:modified});const geometry=x=>JSON.stringify(x.elements.map(({provenance,...e})=>e));assert.notEqual(geometry(r),geometry(changed));
 rows.push({typology,mode,lineageValid:true,descriptorGeometryChanged:true,diagnostic:r.domainDiagnostic});
}
const noChain={...analysis,voids:analysis.voids.filter(v=>v.z===Math.min(...analysis.voids.map(r=>r.z)))};const ids=new Set([...noChain.letters,...noChain.voids].map(r=>r.id));noChain.relationships=noChain.relationships.filter(e=>ids.has(e.fromId)&&ids.has(e.toId));
for(const mode of ['letters','voids','combined']){const r=engine.generateProtoArchitecture({...fixture,typology:'vertical-void-lobby',mode,sourceAnalysis:noChain,quality:'preview'});assert.equal(r.elements.length,0);assert(r.validation.failures.some(s=>s.includes('UNSUPPORTED SOURCE FOR VERTICAL VOID LOBBY')));}
const file=path.join(root,'.typology-matrix-build/src/components/checkpoint.js'),baseline=new Module(file,module);baseline.filename=file;baseline.paths=Module._nodeModulePaths(path.dirname(file));baseline._compile(ts.transpileModule(fs.readFileSync(path.join(root,'checkpoints/2026-09-28-before-provenance/amphitheaterPrototype.ts.checkpoint.txt'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
const legacy=[];for(const typology of ['stepped-amphitheater','void-field-gathering','open-hall-workspace']){const args={...fixture,typology,mode:'combined',quality:'preview'},a=baseline.exports.generateProtoArchitecture(args),b=engine.generateProtoArchitecture(args);assert.deepEqual(b.presentationMesh.positions,a.presentationMesh.positions);assert.deepEqual(b.presentationMesh.indices,a.presentationMesh.indices);legacy.push({typology,previewMeshUnchanged:true});}
fs.writeFileSync(path.join(__dirname,'integrity.json'),JSON.stringify({rows,unsupportedChainAllModes:true,legacy},null,2));console.log('Lineage, descriptor, unsupported-chain and legacy preview checks passed.');
