const fs=require('fs'),path=require('path'),sharp=require('sharp');
const rows=require('./results.json'),causal=require('./causal-checks.json');
const pct=(n,d)=>`${n}/${d} (${(100*n/Math.max(1,d)).toFixed(1)}%)`,xyz=a=>a?.map(x=>x.toFixed(2)).join(' × ')||'unsupported';
rows.sort((a,b)=>a.typology.localeCompare(b.typology)||['letters','voids','combined'].indexOf(a.mode)-['letters','voids','combined'].indexOf(b.mode));
let report='# Provenance correction measurements\n\nAll geometric comparisons exclude provenance and element IDs. The final matrix uses the deterministic 192-letter fixture, seed 2041, fixed descriptors, organic controls and extent.\n\n## Local assignment coverage\n\n| Typology | Mode | Original members | Regions | Relationships | Voids | Source-provenance elements | Fallback elements |\n|---|---|---|---|---|---|---|---|\n';
for(const r of rows){const d=r.diagnostic;report+=`| ${r.typology} | ${r.mode} | ${pct(d.lettersAssigned,d.lettersAvailable)} | ${pct(d.componentsUsed,d.componentsAvailable)} | ${pct(d.relationshipsUsed,d.relationshipsAvailable)} | ${pct(d.voidsAssigned,d.voidsAvailable)} | ${d.provenanceElements} | ${d.fallbackElements} |\n`;}
report+='\nEnvelope-only influence is excluded from assigned-ID numerators. Void-support member IDs indicate nearby bounding letters, not necessarily occupied letter architecture. Source-provenance element totals include explicitly labeled envelope elements.\n\n## Final reconstruction and targeted response\n\n| Typology | Mode | Baseline components | Previous perturbation | Previous cluster removal | Assigned-feature move | Assigned-feature removal | Target geometry changes (move / removal) |\n|---|---|---|---|---|---|---|---|\n';
for(const r of rows){const c=causal.find(x=>x.typology===r.typology&&x.mode===r.mode);report+=`| ${r.typology} | ${r.mode} | ${['base','perturbation','removal','assignedMove','assignedRemoval'].map(k=>r.tests[k].components).join(' | ')} | ${c.tests.assignedMove.actualTargetGeometryChanged?'yes':'NO'} / ${c.tests.assignedRemoval.actualTargetGeometryChanged?'yes':'NO'} |\n`;}
report+='\n## Baseline extents (architectural feet, XYZ)\n\n| Typology | Mode | Source | Raw | Final |\n|---|---|---|---|---|\n';for(const r of rows)report+=`| ${r.typology} | ${r.mode} | ${xyz(r.diagnostic.source)} | ${xyz(r.diagnostic.raw)} | ${xyz(r.diagnostic.final)} |\n`;
report+='\n## Exact feature assignments\n\n';
let html=fs.readFileSync(path.join(__dirname,'SOURCE_INFLUENCE_MAP.html'),'utf8');
for(const r of rows){const name=r.typology+'-'+r.mode,record=JSON.parse(fs.readFileSync(path.join(__dirname,name+'-assignments.json'))),targets=record.elements.filter(e=>e.provenance?.role==='local'&&!e.id.includes('domain-landing')&&!e.id.includes('contained-enclosure'));
 report+=`### ${r.typology} / ${r.mode}\n\nTarget: ${r.target.architecturalElementId}\n\n- Source regions: ${r.target.sourceRegionIds.join(', ')}\n- Source voids: ${r.target.sourceVoidIds.join(', ')||'none'}\n- Source members: ${r.target.sourceLetterIds.join(', ')}\n- Source relationships: ${r.target.sourceRelationshipIds.join(', ')||'none internal to target'}\n\n`;
 const ledger=`<details><summary>All major local assignments: source IDs → architectural element IDs</summary><table><tr><th>Architectural element</th><th>Source regions / voids</th><th>Source edges</th></tr>${targets.map(e=>`<tr><td>${e.id}</td><td>${e.provenance.sourceRegionIds.join('<br>')}</td><td>${e.provenance.sourceRelationshipIds.join('<br>')}</td></tr>`).join('')}</table></details>`;
 html=html.replace(`<a href="${name}-assignments.json">`,`${ledger}<a href="${name}-assignments.json">`);
}
fs.writeFileSync(path.join(__dirname,'MEASUREMENTS.md'),report);
html=html.replace('section{margin-bottom:50px}','section{margin-bottom:50px}td,th{border:1px solid #385057;padding:8px;vertical-align:top}table{border-collapse:collapse;width:100%;font-size:12px}details{margin:18px 0}');fs.writeFileSync(path.join(__dirname,'SOURCE_INFLUENCE_MAP.html'),html);
(async()=>{const types=['contained-room-within-volume','flat-deep-plan-plate','vertical-void-lobby'],modes=['letters','voids','combined'],parts=[];for(let r=0;r<3;r++)for(let c=0;c<3;c++)parts.push({input:await sharp(path.join(__dirname,types[r]+'-'+modes[c]+'-base.svg')).png().toBuffer(),left:c*500,top:r*440});await sharp({create:{width:1500,height:1320,channels:4,background:'#0b161b'}}).composite(parts).png().toFile(path.join(__dirname,'FINAL-COMPARISON.png'));})();
